[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "graph"
authors = [
    {name = "Amiel Iliesi", email = "ailiesi@pdx.edu"}
]
version = "1.0.0"
description = "A generic node graph implementation with basic search."
requires-python = ">= 3.12"
dependencies = ['pytest>=9.1.1', 'numpy>=2.5.3', 'mypy>=2.3.1']
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["graph", "search"]
homepage = "https://github.com/amiel-iliesi"
repository = "https://github.com/amiel-iliesi/PSU_tutoring_materials/tree/main/python/data_structures/graph"

[tool.setuptools.packages.find]
where = ["src"]
